// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnuypbv3sNnRiytt7kbqEj3L3lYV_8Q8',
    appId: '1:325831676092:web:11e254fec5b064a19000b9',
    messagingSenderId: '325831676092',
    projectId: 'ipssiflutter2023',
    authDomain: 'ipssiflutter2023.firebaseapp.com',
    storageBucket: 'ipssiflutter2023.appspot.com',
    measurementId: 'G-PN5S01D21S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-fV5Vp3SWSvo5APG5W0xzllsaffetaY',
    appId: '1:325831676092:android:e1c431167783421a9000b9',
    messagingSenderId: '325831676092',
    projectId: 'ipssiflutter2023',
    storageBucket: 'ipssiflutter2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAST2ekcC5Vz9hSgfY2Cww7dEW7vBUiH2A',
    appId: '1:325831676092:ios:8f3a109db2bfb1b09000b9',
    messagingSenderId: '325831676092',
    projectId: 'ipssiflutter2023',
    storageBucket: 'ipssiflutter2023.appspot.com',
    iosClientId: '325831676092-icf4g5v48vphpg1jmlk65kpar94upvgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAST2ekcC5Vz9hSgfY2Cww7dEW7vBUiH2A',
    appId: '1:325831676092:ios:1617db29c4e4aca29000b9',
    messagingSenderId: '325831676092',
    projectId: 'ipssiflutter2023',
    storageBucket: 'ipssiflutter2023.appspot.com',
    iosClientId: '325831676092-r4qklhmth8fhf2scvh0v9vfun50lqg54.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233.RunnerTests',
  );
}
